#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
## Fuzzy search and open file from commandline
## options:
##      -e, --editor <command>  The editor to use [default: gvim]
##      -d, --directory <path>  The path where to look for files [default: .]
##      -n, --note              If provided, Notes directory will be searched [default: 0]
## see https://gist.github.com/BaseCase/c45299e4f8474119881d708a4b728fbf#file-fuz-sh

# GENERATED_CODE: start
# Default values
_note=0
_editor=gvim
_directory=.

# Converting long-options into short ones
for arg in "$@"; do
  shift
  case "$arg" in
"--editor") set -- "$@" "-e";;
"--directory") set -- "$@" "-d";;
"--note") set -- "$@" "-n";;
  *) set -- "$@" "$arg"
  esac
done

function print_illegal() {
    echo Unexpected flag in command line \"$@\"
}

# Parsing flags and arguments
while getopts 'hne:d:' OPT; do
    case $OPT in
        h) sed -ne 's/^## \(.*\)/\1/p' $0
           exit 1 ;;
        n) _note=1 ;;
        e) _editor=$OPTARG ;;
        d) _directory=$OPTARG ;;
        \?) print_illegal $@ >&2;
            echo "---"
            sed -ne 's/^## \(.*\)/\1/p' $0
            exit 1
            ;;
    esac
done
# GENERATED_CODE: end

set -e

main() {
  previous_file="$1"
  file_to_edit=`select_file $previous_file`

  if [ -n "$file_to_edit" ] ; then
    "$_editor" "$file_to_edit" &
    #main "$file_to_edit"
  fi
}

select_file() {
  given_file="$1"
  fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
}


if [ $_note = 1 ]; then
    echo "Selecting Notes directory"
    _directory=$HOME/Dropbox/Notes
fi

previousdirectory=`pwd`
cd "$_directory"
main ""
cd "$previousdirectory"
