#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
# see https://gist.github.com/BaseCase/c45299e4f8474119881d708a4b728fbf#file-fuz-sh
set -e

main() {
  previous_file="$1"
  file_to_edit=`select_file $previous_file`

  if [ -n "$file_to_edit" ] ; then
    gvim -f "$file_to_edit" &
    #main "$file_to_edit"
  fi
}

select_file() {
  given_file="$1"
  fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
}

curdir=`pwd`
cd ~/Dropbox/Notes/
main ""
cd "$curdir"
