#!/usr/bin/env bash

if ! command -v calcurse /dev/null 2>&1 >/dev/null; then
    sudo dnf install -y calcurse
fi

today_date=$(date "+%A %d %B - %H:%M")
echo "## $today_date"
calcurse -a | grep -v "Home" | grep -v "$(date +%D)"

if false; then
    killall remind >/dev/null 2>&1
    myremind -z1 -k'notify-send --app-name MyRemind -i dialog-information -u normal %s' &
    rc=$?
    if [ $rc -ne 0 ]; then
        echo "[!] Could not start Remind: error $rc"
        exit 1
    fi
    echo "[+] Remind started"
fi
