#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
## Simple interface to `at` to allow the usage as a pomodoro timer.
## usage:
##    pomo help     Show this message
##    pomo start
##    pomo alt
##    pomo

# environment variables
_work_session_time=${POMO_WORK_SESSION_TIME:-25}
_pause_session_time=${POMO_PAUSE_SESSION_TIME:-5}
_log_session_path=${POMO_LOG_SESSION_PATH:-~/Dropbox/Work/sideproject/pomo-session-log.txt}


# functions
function help() {
    cat $0 | grep -e "^##"
}

function begin() {
    d=[[:digit:]]
    session_start_time=`LC_ALL=en_US.utf8 date +"%a %b %d %H:%M:%S %Y"`
    echo "notify-send -i time -c urgent 'work session ended'" | at now + $_work_session_time min >/tmp/pomo.log
}

function end() {
    echo end
}

function status() {
    echo status
    echo "run pomo help for usage"
}

# main
cmd=$1
[ "$cmd" = "" ] && echo status && exit 0
case $cmd in
    "begin") begin;;
    "end") end;;
    "help") help;;
    *) status
esac


