#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
## Simple interface to `at` to allow the usage as a pomodoro timer.
## usage:
##    redtimer help           Show this message
##    redtimer work
##    redtimer log [search] Show redtimer log, eventually filtered by search term
##    redtimer

# environment variables
_work_session_time=${REDTIMER_WORK_SESSION_TIME:-25}
_pause_session_time=${REDTIMER_PAUSE_SESSION_TIME:-5}
_log_session_path=${REDTIMER_LOG_SESSION_PATH:-~/Dropbox/Work/sideproject/redtimer-session-log.txt}


# functions
function help() {
    cat $0 | grep -e "^##"
}

function work() {
    session_start_time=`LC_ALL=en_US.utf8 date +"%a %b %d %H:%M:%S %Y"`
    echo "notify-send -i time -c urgent 'work session ended'; echo work completed, $session_start_time, $_work_session_time min>> $_log_session_path" | at now + $_work_session_time min
}

function pause() {
    echo "notify-send -i time -c urgent 'pause ended'" | at now + $_pause_session_time min
}

function status() {
    atq
    echo "run redtimer help for usage"
}

function log() {
    search="$@"
    if [ "$search" = "" ]; then
        echo "showing full redtimer log history"
        cat "$_log_session_path"
        n=`cat "$_log_session_path" | wc -l`
        echo "$n session(s) completed"
    else
        echo "showing \"$search\" in redtimer history"
        cat "$_log_session_path" | grep "$search"
        n=`cat "$_log_session_path" | grep "$search" | wc -l`
        echo "$n session(s) completed"
    fi
}

# main
cmd=$1
[ "$cmd" = "" ] && status && exit 0
case $cmd in
    "work") work;;
    "pause") pause;;
    "log") log ${@:2};;
    "help") help;;
    "status") status;;
    *) status;;
esac


