#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
#echo "notify-send \"$@\""

# if not input is given, just show all the jobs in the queue with:
# - the time at which the job will fire
# - the job number
# - the command that will be run
if [ -z "$1" ]; then
    source $HOME/.config/cconf/zsh/functions.zsh

    function atq_sort() {
    atq | \
        awk '{system("echo "$1 "  $(date +\"%Y-%m-%d %H:%M\"  --date \""$2" "$3" "$4" "$5" "$6"\")  "$7"  "$8 )}' | \
        sort -k2
    }

    # array of job ids
    declare -a jobids
    declare -a timings
    jobids=($(atq_sort | awk '{print $1}'))
    dates=($(atq_sort | awk '{print $2}' | date +"%Y-%m-%d" -f -))
    fancy_dates=($(atq_sort | awk '{print $2}' | date +"%b/%d/%Y" -f -))
    timings=($(atq_sort | awk '{print $3}'))
    today=$(date +%Y-%m-%d)
    tomorrow=$(date +%Y-%m-%d -d '+1 day')

    tmp=$(mktemp)
    for i in "${!jobids[@]}"; do
        message=$(at -c "${jobids[$i]}" | grep notify | sed -e 's/.*['\''"]\(.*\).*['\''"]/\1/')
        if [[ ${today} == ${dates[$i]} ]]; then
            time_left=$(time_left_in_seconds ${timings[$i]})
            time_left=$(humanizetime ${time_left})
            time_left=$(echo $time_left | cut -d"." -f1)
        else
            # using tomorrow since the difference will count 1 day more otherwise
            diff=$(echo "`date +%s -d ${dates[$i]}` - `date +%s -d ${tomorrow}`"|bc)
            time_left=$(date +%d -d @${diff})d
        fi
        echo "- ${fancy_dates[$i]} ${timings[$i]}/${time_left} (${jobids[$i]}) ${message}" >> ${tmp}
    done

    cat ${tmp}
    exit 0
fi

echo "notify-send \"$@\""

