#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
## Start/Stop my remote ollama server
## options
## -s, --start  Start the remote ollama server
## -p, --stop   Stop the remote ollama server
## -l, --logs   Log the remote ollama server

# CLInt GENERATED_CODE: start
# info: https://github.com/clobrano/CLInt.git

# No-arguments is not allowed
[ $# -eq 0 ] && sed -ne 's/^## \(.*\)/\1/p' "$0" && exit 1

# Converting long-options into short ones
for arg in "$@"; do
  shift
  case "$arg" in
"--start") set -- "$@" "-s";;
"--stop") set -- "$@" "-p";;
"--logs") set -- "$@" "-l";;
  *) set -- "$@" "$arg"
  esac
done

function print_illegal() {
    echo "[!] Unexpected flag in command line $*"
}

# Parsing flags and arguments
while getopts 'hspl' OPT; do
    case "$OPT" in
        h) sed -ne 's/^## \(.*\)/\1/p' "$0"
           exit 1 ;;
        s) _start=1 ;;
        p) _stop=1 ;;
        l) _logs=1 ;;
        \?) print_illegal "$@" >&2;
            echo "---"
            sed -ne 's/^## \(.*\)/\1/p' "$0"
            exit 1
            ;;
    esac
done
# CLInt GENERATED_CODE: end


if [ -n "$_start" ]; then
    ssh personal -- podman start ollama
    exit $?
fi
if [ -n "$_stop" ]; then
    ssh personal -- podman stop ollama
    exit $?
fi
if [ -n "$_logs" ]; then
    ssh personal -- podman logs -f ollama
    exit $?
fi
