#!/usr/bin/env bash
# -*- coding: UTF-8 -*-
: ${TASK:="task"}
FILTER=$@

# note the negate "!"
! command -v termux-setup-storage >/dev/null
is_termux=$?

LIST=list
[[ $is_termux -eq 0 ]] && LIST=list_short

set -x
$TASK $FILTER $LIST
