#!/usr/bin/env bash
# -*- coding: UTF-8 -*-

command -v wl-copy >/dev/null
if [[ $? -ne 0 ]]; then
    echo "[!] could not find wl-copy"
    exit 1
fi

INFO="echo [+]"
ERROR="echo [!]"
command -v notify-send >/dev/null
if [[ $? -eq 0 ]]; then
    INFO="notify-send --app-name wlcopy -i dialog-information"
    ERROR="notify-send --app-name wlcopy -i error"
fi

wl-copy
if [[ $? -eq 0 ]]; then
    $INFO "content copied in clipboard"
else
    $ERROR "copy to clipboard failed ($?)"
fi
