#!/usr/bin/env bash
# XOB: Xdg-Open Bookmark
# Helper tool to open web bookmarks stored in $HOME/.bookmarks file
# each line of the bookmark file is expected to be made of two elements:
# - a keyword
# - the http link
## This script requires the python implementation of yq.

BOOKMARKS="$HOME/Documents/bookmarks.yml"

selection=$(yq 'with(.bookmarks[]; .key = .key + " => " + .link)' "${BOOKMARKS}"| yq '[ .bookmarks[].key]' | column -t -s ' ' | sort | fzf --layout reverse --height=70%)
if [[ -z ${selection} ]]; then
    exit 0
fi
link=$(echo "${selection}" | awk '{print $4}')
xdg-open ${link} 2>&1>/dev/null
